apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      web: component
  template:
    metadata:
      labels:
        web: component
    spec:
      containers:
      - name: client
        image: stephengrider/multi-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
    
