apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: complex-database-persistent-volume-claim
spec:
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
        storage: 2Gi

# here we didn't mentioned any storage class so it 
# pick default storage


      